name: warmly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.0.3
  audioplayers: ^6.1.0
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/ocean_waves.mp3
    - assets/sounds/rain_forest.mp3
    - assets/sounds/tibetan_bowls.mp3
    - assets/sounds/white_noise.mp3